version: '2'
services:
  mongo:
    image: mongo:latest
    command: mongod --storageEngine=wiredTiger
    ports:
      - "27017:27017"
  ethereum:
    build: ./parity/
    environment:
      - CHAIN=kovan
    ports:
      - "18545:8545"
      - "18546:8546"
